name: Deploy

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
#      - name: Copy files to the server
#        run: |
#          rsync -a --progress --human-readable --delete \
#          --exclude-from '.gitignore' \
#          --exclude .gitignore \
#          --exclude .git \
#          --exclude public \
#          . deploy@devshift:~/gour-back/
      - name: Restart the application
        run: |
          ssh zolkinka@92.53.97.252 "pushd /var/www/gour/gour-back && npm install && npm run build && pm2 restart ecosystem.config.js"
