name: tests

on: [push]

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - name: Install node.js
        env:
          NODE_VERSION: 16.14.2
        run: export NVM_DIR="$HOME/.nvm" && . "$NVM_DIR/nvm.sh" --no-use && nvm install $NODE_VERSION
      - name: Install dependencies
        run: npm install
      - name: Lint source code with ESLint
        run: npm run lint
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nvm
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - name: Install node.js
        env:
          NODE_VERSION: 16.14.2
        run: nvm install $NODE_VERSION
      - name: Install dependencies
        run: npm install
      - name: Prettify our source code with Prettier
        run: npm run prettier

